theme: jekyll-theme-midnight
title: The Battle Spire
site_url: https://chriswestwood.github.io/TheBattleSpire/
repo_name: 'chriswestwood/TheBattleSpire'
repo_url: 'https://github.com/chriswestwood/TheBattleSpire'
